### ISSUE TITLE
Usage needs to be edited in Readme

### ISSUE THREAD

**Issue by rdepew** [hotaydev/audit-export#10]
This is a small thing, but it could be important. The **Usage** section of README.md gives the expanded syntax as

`npm audit --json | audit-export --folder <folder_path> --name <file_name.html> --title <HTML_file_title>`

... but in source/index.js, it looks like the filename parameter should be `--file`, not `--name` .

My suggestion would be to keep `--file`, and edit the Readme.

**Comment by TaylorHo** [comment]
Hey @rdepew, thank you!
I haven't noticed it 😅

It's now fixed and was also added a `--help` function to the tool. Released now on version [2.1.0](https://github.com/hotaydev/audit-export/releases/tag/v2.1.0).

**Comment by rdepew** [comment]
Thanks for the quick edit! I like the `--help` option in 2.1.0.
