### ISSUE TITLE
New eslint configuration system

### ISSUE THREAD

**Issue by uchilaka** [hotaydev/audit-export#11]
There's [a new ESLint configuration system available](https://eslint.org/docs/latest/use/configure/configuration-files-new). It's not currently the default, but the system used in the project (`.eslintrc.js`) will be deprecated by eslint `v9.0.0`

<img width="704" alt="image" src="https://github.com/hotaydev/audit-export/assets/2763396/5dc38e26-a96e-4fa9-93de-7c445d7b1753">

The deprecation notice is [here](https://eslint.org/docs/latest/use/configure/configuration-files#:~:text=configuration%20files%20behave%3F-,Warning,-We%20are%20transitioning)

PS: Found my way to this project via `npm-audit-html` and was glad there's a team supporting this. I intend to look into a PR for the eslint config system updates in a bit - just posting this for visibility in case someone else gets to it before I do

**Comment by TaylorHo** [comment]
Changed to [Biome](https://biomejs.dev/), so this no longer needs to be updated.
