### ISSUE TITLE
Report is only text, what am i missing to see the IU when I open the file

### ISSUE THREAD

**Issue by NicoleBWan** [hotaydev/audit-export#15]
Hello, I've ran the command to get the audit report, but when I open the file (using IE, Edge, Chrome) from the base file explorer location, I only get the json text, no user interface.  Am I missing a plugin? 
Thanks in Advance.

**Comment by NicoleBWan** [comment]
I found a work around.  I created a script to run in task runner, when executed the file is correctly created and I am able to view the file in Edge with the displayed interface.

**Comment by TaylorHo** [comment]
Hello @NicoleBWan, thanks for the report!

Can you share with us details about your environment? Whats OS, Browser, and NodeJS version are you using?
