### ISSUE TITLE
Add an option to filter direct dependencies

### ISSUE THREAD

**Issue by amiceli** [hotaydev/audit-export#17]
Some tools like Trivy allow to report only direct or not direct dependencies.
For example when I run `npm audit --json` : 

~~~json
// ...
"name": "ejs",
"severity": "moderate",
"isDirect": true,
// ...
~~~

Can you add an option like `relationship` / `only-direct` to filter dependencies ?

**Comment by TaylorHo** [comment]
Hey @amiceli, thanks for the suggestion!

I'll look into it to include it in the package.

**Comment by amiceli** [comment]
Perfect, thanks @TaylorHo .

**Comment by TaylorHo** [comment]
@amiceli The newly released version brings tags showing if a vulnerability is direct or indirect/transitive, also showing if there's a fix available through the `npm audit fix`. [See the release](https://github.com/hotaydev/audit-export/releases/tag/v2.2.0).

The next version will include search and filtering options.

**Comment by amiceli** [comment]
@TaylorHo Perfect ! New tag in report is very useful.
I will check next version for search but we can close this issue ;).
Thanks ;).

**Comment by TaylorHo** [comment]
Hey @amiceli, just released the [version 3](https://github.com/hotaydev/audit-export/releases/tag/v3.0.0) of the package =D

This adds a search field and filters by severity and tags, as well as some performance improvements (even though it was already really fast).

**Comment by amiceli** [comment]
Thanks you @TaylorHo ;)
I update my projects right now ^^.

**Comment by amiceli** [comment]
@TaylorHo I tried new version in my project.
With version 3 my report is empty, I don't see dependencies in the list.
When I run it with version 2.2.0, I see dependencies direct / indirect etc.

I join both files in this comment, I didn't found why report is empty.

[reports.zip](https://github.com/user-attachments/files/17072271/reports.zip)

**Comment by TaylorHo** [comment]
@amiceli I got the problem! Before releasing I thought that I was able to solve the issue, but in some cases, it doesn't work, it's a small problem related to how data is parsed in HTML/JS.

I'll publish a fix for this soon.

**Comment by amiceli** [comment]
Perfect, it works ;).

**Comment by amiceli** [comment]
@kuncevic Currently I use `npm audit --omit=dev --json | ./node_modules/.bin/audit-export` and it works.

`devDependencies` are ignored.
