### ISSUE TITLE
Severity is ordered alphabetically

### ISSUE THREAD

**Issue by ZsDeak-SAP** [hotaydev/audit-export#18]
![image](https://github.com/user-attachments/assets/d180106e-43f4-4fec-af5c-f732f0c7b771)

**Comment by TaylorHo** [comment]
Hey @ZsDeak-SAP, thank you for the catch!

It was fixed and is already available in [version 2.1.4](https://github.com/hotaydev/audit-export/releases/tag/v2.1.4). It's also already published in NPM 😄
