### ISSUE TITLE
Mandatory Folder Argument

### ISSUE THREAD

**Issue by tapaj** [hotaydev/audit-export#20]
I was generating reports using `npm audit --omit=dev --json | audit-export` to generate the report and it is working as expected.

Then, while integrating it with CI/CD pipeline, I wanted to generate the report with a specific name (not the default `audit-report.html`). At this point, I noticed that the `--folder` argument is mandatory, if `--filename` is passed.

So, these 2 versions, will throw an error `Error: The provided folder does not exist.`

- `npm audit --omit=dev --json | audit-export --file npm-audit-report.html`
- `npm audit --omit=dev --json | audit-export npm-audit-report.html`

The workaround is to provide a `--folder` argument with the current folder. So, the following command works as expected:

- `npm audit --omit=dev --json | audit-export --folder . --file npm-audit-report.html`

Will this be more intuitive, if we update the behaviour to default to the current folder, if only file argument is provided?

**Comment by TaylorHo** [comment]
Hey @tapaj! Yeah, it was the default in older versions of `audit-export`, I didn't like it but it worked.

I just [released version 4](https://www.npmjs.com/package/audit-export/v/4.0.0) of the program, which unifies the `--folder` and `--file` parameters under a unique parameter called `--path`. You can now use only the **folder** or **file** path, or **both paths** together as a single path. This path can also be the **absolute path** or **relative path**.

This is a breaking change between version 3, but it's the best for the package progression and maturity.

Thanks for the issue, hope this new release is useful for you.

**Comment by kuncevic** [comment]
Just got an error `Error: The provided folder does not exist.`

`npm audit --json | audit-export audit-export --title "Project Security Report"` 

Does it make any sense?

**Comment by kuncevic** [comment]
Just got an error `Error: The provided folder does not exist`:

```
npm audit --json | audit-export --title "Project Security Report" .    (base) 
Error: The provided folder does not exist.
```

Does it make any sense?
